
import java.io.BufferedReader;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.logging.Level;
import java.util.logging.Logger;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Domenico
 */
public class Window extends javax.swing.JFrame {
    private String easyFileName = "easywords";
    private String mediumFileName = "mediumwords";
    private String hardFileName = "hardwords";
    private long wordIndex; 
    /**
     */
    private PrintWriter easyFile, mediumFile, hardFile;
    public Window() {
        initComponents();
        setLocationRelativeTo(null);
        initCounters();
        
        easyFile = openWordFile(easyFileName);
        mediumFile = openWordFile(mediumFileName);
        hardFile = openWordFile(hardFileName);
        
    }
    /**Apre il file passato per argomento. Se non è presente o se presente ma vuoto, lo crea inserendo il comando INSERT*/
    private PrintWriter openWordFile(String fileName){
        try{
            BufferedReader reader = new BufferedReader(new FileReader(fileName + ".sql"));
            if(reader.readLine().isEmpty())
                return createNewFile(fileName);
            return new PrintWriter(new FileWriter(fileName + ".sql", true), true);
        }catch(FileNotFoundException ex){
            return createNewFile(fileName);
        }catch(IOException ex){
            return null;
        }
    }
    /**Crea un nuovo file con il nome passato per argomento inserendo il comando INSERT*/
    private PrintWriter createNewFile(String fileName){
        try {
            PrintWriter writer = new PrintWriter(new FileWriter(fileName + ".sql"));
            writer.println("INSERT INTO " + fileName + "(ID, Word, Meaning, Category) VALUES");
            writer.flush();
            return writer;
        } catch (IOException ex) {
            return null;
        }
    }
    private void saveCounters(){
        try{
            PrintWriter writer = new PrintWriter(new FileWriter("save"));
            writer.println(easyWords.getText()); writer.println(mediumWords.getText()); writer.println(hardWords.getText());
            writer.flush();
            writer.close();
        }catch(IOException ex){
            
        }
    }
    /***/
    private void initCounters() {
        try{
            BufferedReader bufferedReader = new BufferedReader(new FileReader("save"));
            easyWords.setText(bufferedReader.readLine()); 
            mediumWords.setText(bufferedReader.readLine());
            hardWords.setText(bufferedReader.readLine());
            wordIndex = Long.parseLong(bufferedReader.readLine());
            bufferedReader.close();
        }catch(Exception ex){
            try {
                PrintWriter writer = new PrintWriter(new FileWriter("save"));
                for(int i=0; i<4; i++)
                    writer.println("0");
                writer.flush();
            } catch (IOException e) {
                
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnEasy = new javax.swing.JButton();
        btnHard = new javax.swing.JButton();
        btnMedium = new javax.swing.JButton();
        txtWord = new javax.swing.JTextField();
        txtMeaning = new javax.swing.JTextField();
        btnNext = new javax.swing.JButton();
        btnNew = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        easyWords = new javax.swing.JLabel();
        mediumWords = new javax.swing.JLabel();
        hardWords = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        btnEasy.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnEasy.setText("Facile");
        btnEasy.setFocusable(false);
        btnEasy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEasyActionPerformed(evt);
            }
        });

        btnHard.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnHard.setText("Difficile");
        btnHard.setFocusable(false);
        btnHard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHardActionPerformed(evt);
            }
        });

        btnMedium.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnMedium.setText("Media");
        btnMedium.setFocusable(false);
        btnMedium.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMediumActionPerformed(evt);
            }
        });

        txtWord.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txtWord.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtWord.setText("Parola");
        txtWord.setFocusable(false);
        txtWord.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtWordMouseClicked(evt);
            }
        });

        txtMeaning.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txtMeaning.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtMeaning.setText("Definizione");
        txtMeaning.setFocusable(false);
        txtMeaning.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtMeaningMouseClicked(evt);
            }
        });

        btnNext.setText("Scarta");
        btnNext.setFocusable(false);

        btnNew.setText("Nuova");
        btnNew.setFocusable(false);
        btnNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewActionPerformed(evt);
            }
        });

        jLabel1.setText("WordSmistor 2000 Developed by HDev");

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Facili");

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Medie");

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Difficili");

        easyWords.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        easyWords.setText("0");

        mediumWords.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mediumWords.setText("0");

        hardWords.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        hardWords.setText("0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtWord)
                    .addComponent(txtMeaning)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnEasy, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(btnMedium, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                        .addComponent(btnHard, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                            .addComponent(easyWords, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                            .addComponent(mediumWords, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                            .addComponent(hardWords, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnNew)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnNext)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnNext)
                        .addComponent(btnNew))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(easyWords)
                            .addComponent(hardWords)
                            .addComponent(mediumWords, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(31, 31, 31)
                .addComponent(txtWord, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtMeaning, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEasy, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMedium, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHard, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(8, 8, 8))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewActionPerformed
        txtMeaning.setFocusable(true);
        txtWord.setFocusable(true);
        txtMeaning.setText("");
        txtWord.setText("");
    }//GEN-LAST:event_btnNewActionPerformed

    private void btnEasyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEasyActionPerformed
        String word = txtWord.getText();
        String meaning = txtMeaning.getText();
        if(!word.isEmpty() && !meaning.isEmpty()){
            if(word != "Parola" && meaning != "Definizione"){
                int count = Integer.parseInt(easyWords.getText());
                if(count > 0)
                    easyFile.append("," + System.getProperty("line.separator"));
                easyFile.append("(" + (count+1) + ",'" + word + "','" + meaning + "'," + "'')");
                easyFile.flush();
                easyWords.setText("" + ++count);
                saveCounters();
            }
        }
    }//GEN-LAST:event_btnEasyActionPerformed

    private void btnMediumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMediumActionPerformed
        String word = txtWord.getText();
        String meaning = txtMeaning.getText();
        if(!word.isEmpty() && !meaning.isEmpty()){
            if(word != "Parola" && meaning != "Definizione"){
                int count = Integer.parseInt(mediumWords.getText()); 
                if(count > 0)
                    mediumFile.append("," + System.getProperty("line.separator"));
                mediumFile.append("(" + (count+1) + ",'" + word + "','" + meaning + "'," + "'')");
                mediumFile.flush();
                mediumWords.setText("" + ++count);
                saveCounters();
            }
        }
    }//GEN-LAST:event_btnMediumActionPerformed

    private void btnHardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHardActionPerformed
        String word = txtWord.getText();
        String meaning = txtMeaning.getText();
        if(!word.isEmpty() && !meaning.isEmpty()){
            if(word != "Parola" && meaning != "Definizione"){
                int count = Integer.parseInt(hardWords.getText());
                if(count > 0)
                    hardFile.append("," + System.getProperty("line.separator"));
                hardFile.append("(" + (count+1) + ",'" + word + "','" + meaning + "'," + "'')");
                hardFile.flush();
                hardWords.setText("" + ++count);
                saveCounters();
            }
        }
    }//GEN-LAST:event_btnHardActionPerformed

    private void txtWordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtWordMouseClicked
        if(txtWord.getText() != "Parola"){
            txtWord.setFocusable(true);
            txtWord.setText("");
        }
    }//GEN-LAST:event_txtWordMouseClicked

    private void txtMeaningMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtMeaningMouseClicked
        if(txtMeaning.getText() != "Definizione"){
            txtMeaning.setFocusable(true);
            txtMeaning.setText("");
        }
    }//GEN-LAST:event_txtMeaningMouseClicked
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Window().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEasy;
    private javax.swing.JButton btnHard;
    private javax.swing.JButton btnMedium;
    private javax.swing.JButton btnNew;
    private javax.swing.JButton btnNext;
    private javax.swing.JLabel easyWords;
    private javax.swing.JLabel hardWords;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel mediumWords;
    private javax.swing.JTextField txtMeaning;
    private javax.swing.JTextField txtWord;
    // End of variables declaration//GEN-END:variables
}
